---
- name: ensure php packages
  become: true
  package:
    state: "{{ pkg_state|default('present') }}"
    name: "{{ item }}"
  loop:
    - unzip
    - php
    - php-sqlite
    - xdebug


- name: php.ini settings
  become: true
  lineinfile: 
    dest: '/etc/php/php.ini'
    line: "{{ item }}"
  loop: 
    - 'date.timezone=Europe/Berlin'
    - 'extension=iconv'
    - 'zend_extension=xdebug.so'
    - 'xdebug.remote_enable=on'
    - 'xdebug.remote_host=127.0.0.1'
    - 'xdebug.remote_port=9000'
    - 'xdebug.remote_handler=dbgp'
    - 'xdebug.cli_color = 2'


- name: check if composer is installed
  stat: 
    path: /usr/local/bin/composer
  register: composer_state

- block:
  - name: get composer signature
    uri:
      url: https://composer.github.io/installer.sig
      return_content: true
    register: composer_sig
  - name: download installer
    become: true
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/composer-setup.php
      checksum: "sha384:{{ composer_sig.content }}"
  - name: install composer
    become: true
    command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  when: composer_state.stat.exists == false

#    - name: copy xdebug script
#      become: true
#      copy:
#        src: xdebug
#        dest: /usr/local/bin/xdebug
#        mode: 0755
