---
- name: get tarball name
  shell: curl -sS http://www.sublimetext.com/3 | grep -o -E 'sublime_text_3_build_.*_x64\.tar\.bz2'
  register: sublime_tarball_name

- debug: var=sublime_tarball_name

- name: download sublime tarball
  get_url:
    url: "https://download.sublimetext.com/{{ sublime_tarball_name.stdout }}"
    dest: /tmp/sublime.tar.bz2

- name: unarchive sublime tarball
  become: true
  unarchive:
    src: /tmp/sublime.tar.bz2
    dest: /opt
    remote_src: true

- name: link subl command
  become: true
  file:
    src: "/opt/sublime_text_3/sublime_text"
    dest: /usr/local/bin/subl
    state: link
