---

- name: ensure nibelheim mount dir
  file: dest={{ item.path }} state=directory
  loop: "{{ nfs_client_mounts }}"

- name: mount nibelheim
  mount:
    path: "{{ item.path }}"
    src: "UUID={{ item.uuid }}"
    fstype: "{{ item.fs }}"
    state: mounted
  loop: "{{ nfs_client_mounts }}"


- name: ensure nibelheim is exported
  lineinfile:
    path: /etc/exports
    regexp: '^{{ item.path }}'
    line: "{{ item.path }}/ 192.168.178.0/24(rw,sync)"
    create: yes
  notify: [restart nfs services]
  loop: "{{ nfs_client_mounts }}"
  
- name: enable nfs services
  service:
    name: "{{ item }}"
    enabled: yes
  notify: [restart nfs services]
  loop: 
    - rpcbind
    - nfs-server




#/files/ *(ro,sync) # Nur-Lese Rechte für jedermann
#/files/ 192.168.0.100(rw,sync) # Schreib-Lese Rechte für einen Client auf 192.168.0.100
#/files/ 192.168.1.1/24(rw,sync) # Schreib-Lese Rechte für alle Clienten von 192.168.1.1 bis 192.168.1.255 