---
- hosts: all
  gather_facts: false
  tags: [always]
  pre_tasks:
    - name: ensure python
      raw: sudo bash -c "test -e /usr/bin/python || (pacman -S --noconfirm python)"

- import_playbook: playbooks/aerith.yml
- import_playbook: playbooks/cait-sith.yml


#- host: init
#  roles:
#    - { role: packages/system, become: true }
