---
- name: ensure dhcp service is enabled
  service:
    name: dhcpcd
    enabled: yes
  notify:
    - restart dhcp

- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  when: ansible_distribution != 'Archlinux'

- name: set hostname on archlinux
  lineinfile:
    path: /etc/hostname
    line: "{{ inventory_hostname }}"
    create: yes
  when: ansible_distribution == 'Archlinux'

- name: place this host in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ inventory_hostname }}"

- name: place other hosts in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ item.ip }} {{ item.host }}"
  loop: "{{ desktop_system_hosts }}"
  when: item.host != inventory_hostname


- name: ensure base packages
  become: true
  package:
    state: "{{ pkg_state|default('present') }}"
    name: "{{ desktop_system_packages }}"
