---
- name: Check if git is installed
  command: type git
  register: ko_check_git
  ignore_errors: true

- name: set git install state fact
  set_fact:
    ko_git_configure: ko_check_git.result

- name: Check if zsh is installed
  command: type zsh
  register: ko_check_zsh
  ignore_errors: true

- name: set zsh install state fact
  set_fact:
    ko_zsh_configure: ko_check_zsh.result



# git clone git://github.com/doceme/py-spidev
# cd py-spidev/
# sudo python setup.py install
