---
- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [always]

- name: include init system scripts
  become: true
  include: init_system.yml
  tags: [init, system]

- debug: var=ko_packages

- name: ensure additional packages
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ ko_packages }}"

- name: install aur packages
  include_role:
    name: aur
  vars:
    pkg_name: "{{ item }}"
  with_items: "{{ ko_aur_packages }}"
  when: ansible_distribution == "Archlinux"

- name: Get ko facts
  include: facts.yml
  tags: [always]

- name: include init user scripts
  become: true
  include: init_user.yml
  tags: [init, user]
  when: ko_user_configure|default(false)

- name: include locale scripts
  include: locale.yml
  when: ko_locale_configure
  tags: [locale]

- debug: var=ko_user_configure
- debug: var=ko_git_configure

- name: include git scripts
  include: git.yml
  when: ko_git_configure|default(false) and ko_user_configure|default(false)
  tags: [git]

- name: include zsh scripts
  include: zsh.yml
  when: ko_zsh_configure|default(false) and ko_user_configure|default(false)
  tags: [zsh]

- name: include project scripts
  include: project.yml
  when: ko_project_path|default(false) and ko_user_configure|default(false)
  tags: [project]

- name: ensure virtual box guest additions
  become: true
  pacman:
    name: "{{ item }}"
    state: latest
  with_items: 
    - virtualbox-guest-utils
    #- virtualbox-guest-modules-arch
  when: (ansible_virtualization_role == "guest") and
        (ansible_virtualization_type == "virtualbox") and 
        (ansible_distribution == "Archlinux")
