---
- name: get sublimetext3 gpg key
  uri:
    url: "https://download.sublimetext.com/sublimehq-pub.gpg"
    dest: /tmp/sublimehq-pub.gpg
    timeout: 6
  register: sublimetext3_pacman_key


- name: ensure gpg keys
  become: true
  shell: pacman-key --add /tmp/sublimehq-pub.gpg  && pacman-key --lsign-key 8A8F901A

- name: sublimetext3 pacman channel
  become: true
  ini_file:
    dest:    /etc/pacman.conf
    section: sublime-text
    option:  Server
    value:   https://download.sublimetext.com/arch/stable/x86_64
  register: sublimetext3_update_pacman

- name: sublimetext3 is installed
  become: true
  package:
    update_cache: yes
    state: latest
    name: sublime-text
