---
- name: get sublimetext3 key content
  uri:
    url: "https://download.sublimetext.com/sublimehq-pub.gpg"
    return_content: yes
    timeout: 6
  register: sublimetext3_pacman_key

# Install the GPG key:
- name: ensure sublimetext3 pacman keys
  become: true
  shell: pacman-key --add sublimehq-pub.gpg && pacman-key --lsign-key 8A8F901A


# curl -O https://download.sublimetext.com/sublimehq-pub.gpg &&
#   sudo pacman-key --add sublimehq-pub.gpg &&
#   sudo pacman-key --lsign-key 8A8F901A &&
#   rm sublimehq-pub.gpg


# Select the channel to use:

#echo -e "\n[sublime-text]\nServer = https://download.sublimetext.com/arch/stable/x86_64" | sudo tee -a /etc/pacman.conf


# Update pacman and install Sublime Text

#sudo pacman -Syu sublime-text



# - name: sublimetext3 is installed
#   include_role:
#     name: ko/aur
#   vars:
#     pkg_name: sublime-text-dev
