---
- name: ensure user related systemd config dir
  file:
    path: "{{ nest_user_home }}/.config/systemd/user/"
    state: directory

- name: ensure nest systemd configs
  template:
    src: "{{ item.src }}"
    dest: "{{ nest_user_home }}/.config/systemd/user/{{ item.dest }}"
  with_items: 
    - { src: nest.timer, dest: nest.timer }
    - { src: nest.service, dest: nest.service }

- name: start nest autorun
  systemd:
    enabled: true
    daemon_reload: yes
    name: nest.timer
    user: true
  notify: restart nest autorun

# todo: find nice solution for this
- name: ensure export PATH to systemd
  copy:
    src: systemd-import-path.zsh
    dest: "{{ ko_zsh_custom_dir }}/systemd-import-path.zsh"
