---
- name: install git
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items: 
    - git
    - tig

- name: ensure git config
  become: true
  become_user: "{{ nest_user_name }}"
  ini_file:
    dest:    "{{ nest_user_home }}/.gitconfig"
    section: "{{ item.ns }}"
    option:  "{{ item.name }}"
    value:   "{{ item.value }}"
  with_items:
    -
      ns:    user
      name:  email
      value: "{{ nest_git_mail }}"
    -
      ns:    user
      name:  name
      value: "{{ nest_git_user|default(nest_user_name) }}"
    -
      ns:    push
      name:  default
      value: simple
    -
      ns:    core
      name:  excludesfile
      value: "{{ nest_user_home }}/.gitignore"
