---
# tasks file for aweseometheme- name: place awesome config files
- name: ensure configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "ko_widgets",   dest: "{{ awesometheme_dir }}/" }
    - { src: "theme",   dest: "{{ awesometheme_dir }}/" }

- name: ensure rc files
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: rc.lua.j2, dest: "{{ awesometheme_dir }}/rc.lua" }
