---
- name: install awesome packages
  pacman:
    name: "{{ item }}"
    state: latest
  when: ansible_pkg_mgr == "pacman"
  with_items:
    - xorg-server
    - xorg-xinit
    - xorg-utils
    - xorg-server-utils
    - xf86-video-vesa
    - alsa-utils
    - xbindkeys
    - awesome
    - vicious
    - xterm
    - qt4
    - iw
    #- xorg-xdm
    - qiv
    - ntp
    - acpi
  # fonts
    - terminus-font
    - ttf-dejavu
    - ttf-inconsolata
    - ttf-bitstream-vera
    - ttf-linux-libertine

- name: ensure x11 configurations
  template:
    src: "{{ item.src }}"
    dest: "/etc/X11/xorg.conf.d/{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items: 
    - 
      src: x11-monitor.conf.j2
      dest: 20-monitor.conf
    - 
      src: x11-keyboard.conf.j2
      dest: 20-keyboard.conf
