---
- name: ensure root login is disabled
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: PermitRootLogin no
    regexp: "^PermitRootLogin.*$"
  notify:
    - restart ssh

- name: ensure ssh service is enabled
  service:
    name: sshd
    enabled: yes
  notify:
    - restart ssh
