---
# tasks file for aweseometheme- name: place awesome config files
- name: ensure configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "widgets",   dest: "{{ awesometheme_dir }}/" }
    - { src: "theme",   dest: "{{ awesometheme_dir }}/" }

- name: ensure rc files
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
#    - { src: "{{ awesometheme_theme }}.lua.j2", dest: "{{ awesometheme_dir }}/rc.lua" }
    - { src: "rc.lua.j2", dest: "{{ awesometheme_dir }}/rc.lua" }
