---
- name: ensure easy_install
  become: true
  package:
    name: python-setuptools
    state: latest

- name: ensure pip
  become: true
  easy_install:
    name: pip
    state: latest  

- name: ensure ansible
  become: true
  pip:
    name: "{{ item }}"
    state: latest
  with_items: 
    - ansible
