---
- include: thinkfan.yml
  tags: [thinkfan]

- include: sound.yml
  tags: [sound]

- include: graphics.yml
  tags: [graphics]

- name: install thinkpad related packages
  become: true
  pacman: 
    name: "{{ item }}"
    state: latest
  with_items:
    - xf86-input-libinput
    - libdvdread
    - libdvdcss
    - libdvdnav
  when: ansible_pkg_mgr == "pacman"

- name: place touchpad toggle scripts
  become: true
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root 
    group: root 
    mode: 0755
  with_items: 
    - { src: touchpad_toggle.sh, dest: /usr/local/bin/touchpad_toggle.sh }
    - { src: touchpad_status.sh, dest: /usr/local/bin/touchpad_status.sh }

