---
#- name: install thinkfan packages
#  include_role:
#    name: aur
#  vars:
#    pkg_name: thinkfan
#  when: ansible_distribution == "Archlinux"

- name: install thinkpad thinkfan packages
  become: true
  pacman: 
    name: "{{ item }}"
    state: latest
  with_items:
    - acpid
    - lm_sensors
  when: ansible_pkg_mgr == "pacman"

# hack around "bug" with ansible on rbpi
- block:
    - name: install thinkfan packages
      include_role:
        name: aur
      vars:
        pkg_name: thinkfan
  when: ansible_distribution == "Archlinux"

- name: run lm_sensors
  become: true
  command: sensors-detect --auto
  args:
    creates: /etc/conf.d/lm_sensors

- name: find sensor files
  find:
    paths: /sys/devices
    patterns: temp*_input
    file_type: file
    recurse: true
  register: thinkpad_temp_sensors

- name: place thinkpad fan config
  become: true
  template:
    src: thinkfan.fan.conf.j2
    dest: /etc/thinkfan.conf
    owner: root 
    group: root 
    mode: 0644
  notify:
    - restart thinkfan

- name: setup thinkfan modprobe config
  become: true
  copy: 
    src: thinkfan.modprobe.conf 
    dest: /etc/modprobe.d/thinkfan.conf
    owner: root 
    group: root 
    mode: 0644
  notify:
    - restart thinkfan

- name: setup thinkfan modprobe config
  become: true
  modprobe: 
    name: thinkpad_acpi
    params: "fan_control=1"
    state: present
  notify:
    - restart thinkfan

- name: ensure thinkfan is running
  become: true
  service: 
    name: thinkfan 
    enabled: true
  notify:
    - restart thinkfan

- name: ensure acpid is running
  become: true
  service: 
    name: acpid 
    enabled: true
  notify:
    - restart acpid
