---
- name: place xmodmap
  lineinfile:
    path: "{{ ko_user_home }}/.xmodmap.conf"
    regexp: "^keycode {{ item.key }} ="
    line:  "keycode {{ item.key }} = {{ item.action }}"
    create: true
  loop:
    - { key: 114, action: XF86AudioLowerVolume }
    - { key: 115, action: XF86AudioRaiseVolume }


#
#- name: place volume button configs
#  become: true
#  template:
#    src: "{{ item.src }}"
#    dest: "{{ item.dest }}"
#    owner: root 
#    group: root 
#    mode: 0644
#  loop:
#    - { src: acpi.events.vol-d, dest: /etc/acpi/events/vol-d }
#    - { src: acpi.events.vol-u, dest: /etc/acpi/events/vol-u }
#  notify:
#    - restart acpid    


# stuff for daskeyboard q software. Does not work currently
#- name: create install dir
#  file:
#    state: directory
#    dest: /tmp/daskeyboard
#- name: ensure debtap
#  include_role:
#    name: ko/aur
#  vars:
#    pkg_name: debtap
#
#- name: update deptab database
#  become: true
#  shell: debtap -u
#
#- name: download daskeyboard deb file
#  get_url:
#    url: https://download.daskeyboard.com/q-software-releases/3.2.3/das-keyboard-q_3.2.3.deb 
#    dest: /tmp/daskeyboard/das-keyboard-q.deb
#
#- name: convert daskeyboard dep with debtap
#  shell: debtap -Q /tmp/daskeyboard/das-keyboard-q.deb
#  args:
#    chdir: "/tmp/daskeyboard"
#
#- name: convert daskeyboard dep with debtap
#  shell: pacman --noconfirm --noprogressbar --needed -U *.pkg.tar.xz
#  args:
#    chdir: "/tmp/daskeyboard"
#
