---
- name: install thinkpad related packages
  become: true
  pacman: 
    name: "{{ item }}"
    state: latest
  with_items:
    - xf86-video-intel
    - xf86-input-synaptics
    - acpid
    - lm_sensors
    - pulseaudio
  when: ansible_pkg_mgr == "pacman"

- name: install aur packages
  include_role:
    name: aur
  vars:
    pkg_name: thinkfan
  when: ansible_distribution == "Archlinux"

- name: run lm_sensors
  become: true
  command: sensors-detect --auto
  args:
    creates: /etc/conf.d/lm_sensors

- name: find sensor files
  find:
    paths: /sys/devices
    patterns: temp*_input
    file_type: file
    recurse: true
  register: thinkpad_temp_sensors

- name: place thinkpad fan config
  become: true
  template:
    src: thinkfan.fan.conf.j2
    dest: /etc/thinkfan.conf
    owner: root 
    group: root 
    mode: 0644
  notify:
    - restart thinkfan

- name: setup thinkfan modprobe config
  become: true
  copy: 
    src: thinkfan.modprobe.conf 
    dest: /etc/modprobe.d/thinkfan.conf
    owner: root 
    group: root 
    mode: 0644
  notify:
    - restart thinkfan

- name: setup thinkfan modprobe config
  become: true
  modprobe: 
    name: thinkpad_acpi
    params: "fan_control=1"
    state: present
  notify:
    - restart thinkfan

- name: setup sound modprobe config
  become: true
  modprobe: 
    name: snd-hda-intel 
    params: "model=thinkpad" 
    state: present

- name: ensure acpid is running
  become: true
  service: 
    name: acpid 
    enabled: true
  notify:
    - restart acpid

- name: ensure thinkfan is running
  become: true
  service: 
    name: thinkfan 
    enabled: true
  notify:
    - restart thinkfan
