---
- name: place nest repo
  git:
    repo: git@github.com:kolibri/nest.git
    dest: "{{ nest_path }}"
    force: yes
    accept_hostkey: yes

- name: ensure inventory dir
  file:
    dest: "{{ nest_inventory_path }}"
    state: directory

- name: place inventory file
  template:
    src: inventory.j2
    dest: "{{ nest_inventory_path }}/hosts"

- include: copy_config.yml
  when: nest_copy_configuration|default(false)

- include: autorun.yml
  when: nest_autorun|default(false)
