---

- name: setup system for awesomewm
  become: true
  include: system.yml

- name: place awesome config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "user/xinitrc",   dest: "{{ system_user_info.home }}/.xinitrc" }
    - { src: "user/Xdefaults", dest: "{{ system_user_info.home }}/.Xdefaults" }
    - { src: "user/Xresources", dest: "{{ system_user_info.home }}/.Xresources" }
    - { src: "user/startx.zsh", dest: "{{ awesome_startx_dir }}/zz_startx.zsh" }
