---
- hosts: aerith
  roles:
    - { role: ko/base, become: true, tags: [init] }
    - { role: ko/locale, become: true }
    - ko/git
    - ko/zsh
    - ko/awesomewm
    - ko/sublimetext3
    - ko/nest
    - ko/daskeyboard # not finished

  tasks:
    # @todo: update pacman after this / move this out
    - name: enable multilib for steam
      become: true
      ini_file:
        dest:    /etc/pacman.conf
        section: multilib
        option:  Include
        value:   /etc/pacman.d/mirrorlist

    - name: ensure base packages
      become: true
      package:
        state: latest
        name:
          - chromium
          - keepassx2
          - steam
          - wqy-zenhei # from steam
          - vagrant
          - packer

- hosts: aerith.ko
  roles:
    - ko/virtualbox

  tasks:
    - name: ensure base packages for aerith
      become: true
      package:
        state: latest
        name:
          - pulseaudio
          - nvidia
          - nvidia-utils
          - lib32-nvidia-utils

#    - name: setup sound modprobe config
#      become: true
#      modprobe:
#        name: snd-hda-intel
#        params: "model=thinkpad"
#        state: present
