---
  # used as media center and file server
- hosts: aerith
  gather_facts: true
  roles:
    - { role: desktop/system, become: yes }
    - desktop/awesomewm
    - desktop/awesometheme
    - desktop/steam
    - desktop/sublimetext3
    - packages/php-dev
    - packages/virtualbox
    - { role: packages/aur, pkg_name: keepassx2 }
    - { role: packages/aur, pkg_name: phpstorm }
    - { role: packages/aur, pkg_name: mprime }
#    - desktop/daskeyboard # not finished
#    - dev/arduino
