---
  # used as media center and file server
- hosts: caitsith
  gather_facts: true
  roles:
    - { role: desktop/system, become: yes }
    - { role: desktop/awesomewm }
    - { role: desktop/awesometheme }
    - { role: desktop/steam }
    - { role: desktop/nfs }
    - { role: packages/aur, pkg_name: qt4 }
    - { role: packages/aur, pkg_name: keepassx2 }
