---
  # used as media center and file server
- hosts: caitsith
  gather_facts: true
  roles:
    - { role: desktop/system, become: yes }
    
    - { role: desktop/awesomewm }
    - { role: desktop/awesometheme }
    - { role: desktop/steam }
    - { role: packages/gitlab }
