---
- hosts: cid
  gather_facts: true
  roles:
    - { role: desktop/system, become: yes }
    - { role: desktop/awesomewm }
    - { role: desktop/awesometheme }
    - { role: desktop/steam }
    - { role: desktop/sublimetext3 }
