---
- name: install git
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - tig

- name: ensure git config
  ini_file:
    dest:    "{{ ko_user_home }}/.gitconfig"
    section: "{{ item.ns }}"
    option:  "{{ item.name }}"
    value:   "{{ item.value }}"
  with_items:
    - { ns: user, name: email,        value: "{{ ko_git_mail }}" }
    - { ns: user, name: name,         value: "{{ ko_git_user }}" }
    - { ns: push, name: default,      value: simple }
    - { ns: core, name: excludesfile, value: "{{ ko_user_home }}/.gitignore" }

- name: place publickey at github
  github_key:
    name: "SSH Key for {{ ansible_nodename }} (added via ansible)"
    pubkey: "{{ ko_user_info.ssh_public_key }}"
    token: "{{ ko_github_access_token }}"
  when: ko_github_access_token|default(false)
